# Generated by Django 2.2.7 on 2019-11-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfiles'},
        ),
    ]
