# Generated by Django 2.2.7 on 2019-11-28 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='vote',
            field=models.DateField(max_length=12, null=True, verbose_name='Que fecha sera la carnita?'),
        ),
    ]
