# Generated by Django 2.2.6 on 2019-10-22 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='email4',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Cuarto invitado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email5',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Quinto invitado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email6',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Sexto invitado'),
        ),
        migrations.AlterField(
            model_name='event',
            name='email7',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Septimo invitado'),
        ),
    ]
