# Generated by Django 2.2.7 on 2019-11-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_auto_20191125_0002'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayevent',
            options={'verbose_name_plural': 'Votos'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name_plural': 'Eventos'},
        ),
        migrations.AlterModelOptions(
            name='results',
            options={'verbose_name_plural': 'Resultados'},
        ),
        migrations.AlterField(
            model_name='dayevent',
            name='vote',
            field=models.CharField(choices=[(1, 1), (2, 2), (3, 3)], max_length=1, verbose_name='Que fecha sera la carnita'),
        ),
    ]
