# Generated by Django 2.2.7 on 2019-11-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20191125_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='vote',
            field=models.IntegerField(choices=[('Segunda Fecha', 1), (2, 2), (3, 3)], verbose_name='Que fecha sera la carnita'),
        ),
    ]
