# Generated by Django 2.2.7 on 2019-11-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0005_auto_20191125_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayevent',
            name='vote',
            field=models.IntegerField(verbose_name='Que fecha sera la carnita'),
        ),
    ]
